apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create_verify/$', views.create_verify, name='create_verify'),
    url(r'^update_user/(?P<id>\d+)/$', views.update_user, name='update_user'),
    url(r'^show/(?P<id>\d+)/$', views.show, name='show'),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
]

route/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

apps/users/models.py
from django.db import models
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


# Create your models here.
class UserManager(models.Manager):

    def validate_update(self, form):
        '''Validates only if email is the same as original'''
        errors = []
        if len(form['f_name']) < 2:
            errors.append('First Name must have more than 2 characters')
        if len(form['l_name']) < 2:
            errors.append('Last Name must have more than 2 characters')
        return errors

    def validate(self, form):
        '''Validates new user objects creation and updated
        objects only when email is different from original
        in view update_user function'''
        errors = []
        if len(form['f_name'])<2:
            errors.append('First Name must have more than 2 characters')
        if len(form['l_name'])<2:
            errors.append('Last Name must have more than 2 characters')

        if not EMAIL_REGEX.match(form['email']):
            errors.append('Email must be valid')
        email_list = self.filter(email=form['email'])
        if len(email_list) > 0:
            errors.append('Email already in use')
        return errors

    def create_user(self, form):
        """Creates a brand new user"""
        user = self.create(
            f_name = form['f_name'].capitalize(),
            l_name = form['l_name'].capitalize(),
            email = form['email'],
        )
        return user

class User(models.Model):
    f_name = models.CharField(max_length=255)
    l_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __str__(self):
        f = f'{self.f_name} {self.l_name} {self.email}'
        return f

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .models import User


# Create your views here.
def index(request):
    """Renders all users in a user list"""
    all_users = User.objects.all()

    context = {
        'all_users':all_users
    }
    return render(request, 'users/users_list.html', context)


def new(request):
    return render(request, 'users/new.html')

def update_user(request, id):
    '''Gets user from Edit.html and verifies if email is the same,
    if it is, validates at models.validate_update, else goes to
    models.validate.
    Then if errors are found it displays the errors, else saves the
    new values for the user and displays them.'''

    if User.objects.get(id=id).email==request.POST['email']:
        errors = User.objects.validate_update(request.POST)
    else:
        errors = User.objects.validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error)
    else:
        user = User.objects.get(id=id)
        user.l_name = request.POST['l_name'].capitalize()
        user.f_name = request.POST['f_name'].capitalize()
        user.email = request.POST['email']
        user.save()


    context = {
        'id': id,
        'f_name': User.objects.get(id=id).f_name,
        'l_name': User.objects.get(id=id).l_name,
        'email': User.objects.get(id=id).email,
        'created': User.objects.get(id=id).updated_at
    }
    return render(request, 'users/edit.html', context)

def create_verify(request):
    '''Creates a user object from user_list.html verifies
    the data in User.objects.validate in the models.py file.
    Then creates the user objects from User.objects.create_user in the
    models.py file'''
    errors = User.objects.validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error)
    else:
        user = User.objects.create_user(request.POST)
        request.session['user_id'] = user.id
    return redirect('/users/new')

def show(request, id):
    '''creates a temp dict object to render the specific id
    of the user clicked on for more detailed info'''
    context = {
        'id' : id,
        'f_name': User.objects.get(id=id).f_name,
        'l_name': User.objects.get(id=id).l_name,
        'email': User.objects.get(id=id).email,
        'created': User.objects.get(id=id).created_at,
    }
    return render(request,'users/user.html', context)

def delete(request, id):
    """Deletes specific user object"""
    dead = User.objects.get(id=id)
    dead.delete()
    return redirect('/users/index/')

def edit(request, id):
    '''creates a temp dict object to render the specific id
    of the user clicked on to edit user'''
    context = {
        'id' : id,
        'f_name': User.objects.get(id=id).f_name,
        'l_name': User.objects.get(id=id).l_name,
        'email': User.objects.get(id=id).email,
        'created': User.objects.get(id=id).created_at,
    }
    return render(request, 'users/edit.html', context)

apps/users/templates/users/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
</head>
<body>
    <div class="container">
            {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
        <h1>Edit User {{ id}}</h1>
        <form action="/users/update_user/{{ id }}/" method="post">
            {% csrf_token %}
            <div class="form-group">
            <label for="f_name">First Name:</label>
            <input type="text" class="form-control" name="f_name" value="{{ f_name }}">
            </div>
            <div class="form-group">
            <label for="l_name">Last Name:</label>
            <input type="text" class="form-control" name="l_name" value="{{ l_name }}">
            </div>
            <div class="form-group">
            <label for="email">Email:</label>
            <input type="text" class="form-control" name="email" value="{{ email }}">
            </div>
            <input type="submit" name="Create">
        </form>
        <a href="/users/index/">Show All</a>
        <a href="/users/show/{{ id }}">Show user</a>
    </div>
</body>
</html>

apps/users/templates/users/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="container">
        <h1>Add a new user</h1>
        <form action="/users/create_verify/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="f_name">First Name:</label>
                <input type="text" class="form-control" name="f_name">
            </div>
            <div class="form-group">
                <label for="l_name">Last Name:</label>
                <input type="text" class="form-control" name="l_name">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email">
            </div>
            <input type="submit" name="Create">
        </form>
        <a href="{% url 'users:index' %}">Go Back</a>
    </div>
</body>
</html>

apps/users/templates/users/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
</head>
<body>
<div class="container">
    <h1>User {{ id }}</h1>
    <p>Full Name: {{ f_name }} {{ l_name }}</p>
    <p>Email: {{ email }}</p>
    <p>Created at: {{ created }}</p>

    <a href="/users/edit/{{ id }}">Edit</a> | <a href="/users/delete/{{ id }}">Delete</a>
</div>
</body>
</html>

apps/users/templates/users/users_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <!--<link rel="stylesheet" type="text/css" href="main.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>Users</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for name in all_users %}
                <tr>
                    <td>{{ name.id }}</td>
                    <td>{{ name.f_name }} {{ name.l_name }}</td>
                    <td>{{ name.email }}</td>
                    <td>{{ name.created_at }}</td>
                    <td><a href="/users/show/{{ name.id }}">Show</a>
                        <a href="/users/edit/{{ name.id }}">Edit</a>
                        <a href="/users/delete/{{ name.id }}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'users:new' %}">Add a new user</a>
    </div>
</body>
</html>